{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-opencti-exporter.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-opencti-exporter.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    {{- if .Values.serviceMonitor.namespace }}
    - {{ .Values.serviceMonitor.namespace }}
    {{- else }}
    - {{ .Release.Namespace }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-opencti-exporter.selectorLabels" . | nindent 6 }}
  jobLabel: {{ template "prometheus-opencti-exporter.fullname" . }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    - port: {{ .Values.service.portName }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.serviceMonitor.path }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
          metricRelabelings: {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
          relabelings: {{ toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- if .Values.serviceMonitor.tlsConfig }}
          tlsConfig:
      {{ toYaml .Values.serviceMonitor.tlsConfig | indent 6 }}
      {{- end }}
{{- end }}
